name = "callsun-b2b"
main = "src/worker.js"
compatibility_date = "2026-07-23"
compatibility_flags = ["global_fetch_strictly_public", "nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
